### ISSUE TITLE
Hover effect on empty blocks of calender

### ISSUE THREAD

**Issue by jahir-raihan** [jahir-raihan/calendar-generator#1]
### It seems that Hover effect on empty calendar blocks aren't disabled. 

For example hover effect should be only on dates not on empty blocks of dates.

**Expected behaviour with hover :** 

![Screenshot 2023-08-23 at 7 02 04 PM](https://github.com/jahir-raihan/calendar-generator/assets/78207450/ce8a0c5e-e073-4efc-916a-966ed5a73422)

**Current behaviour of hover on empty blocks:** 

![Screenshot 2023-08-23 at 7 01 53 PM](https://github.com/jahir-raihan/calendar-generator/assets/78207450/f3c9404d-b71a-41c7-8fac-9d6e02f7f4ea)

### Hint
> - This problem can be fixed by modifying javascript code when we are generating empty <li></li> elements for week day fill up issue.

**Comment by devbytemehedi** [comment]
@jahir-raihan hey i am beginner web developer learning javascript will i be able to work on this ?

**Comment by jahir-raihan** [comment]
Sure, try your best. I will be there to assist you on the way.

**Comment by Axxi3** [comment]
can i try this or is it assigned???

**Comment by jahir-raihan** [comment]
@Axxi3 Try your best, no one is assigned.

**Comment by Axxi3** [comment]
@devbytemehedi hey man i fixed the code i am giving a pull request please review the changes.
