### ISSUE TITLE
Active date background is still visible after downloading Calendar as pdf.

### ISSUE THREAD

**Issue by jahir-raihan** [jahir-raihan/calendar-generator#13]
## Hint

> - Inside download function remove active class from date box when download button is clicked.
> - And when download finishes, revert back to its original state.

**Current PDF overview after download:** 

![Screenshot 2023-08-25 at 7 23 37 PM](https://github.com/jahir-raihan/calendar-generator/assets/78207450/e4f4e1cd-274b-42b6-9d96-dfba026db6cc)

**Comment by KWangechi** [comment]
Issue has been fixed, see PR #17

**Comment by jahir-raihan** [comment]
@KWangechi  Your PR is being merged, stay up in the loop . Thanks for your contribution.
