### ISSUE TITLE
Download button breaks on certain mobile width

### ISSUE THREAD

**Issue by jahir-raihan** [jahir-raihan/calendar-generator#16]
## Hint 

> - Add/ Edit media query properties for download button.

**Current Situation**
![1692980519737](https://github.com/jahir-raihan/calendar-generator/assets/78207450/4345208f-0533-427b-a754-e918e28453b9)

**Comment by Kkotiswar** [comment]
Is it Resolved already or I have to do any work ?

**Comment by jahir-raihan** [comment]
@Kkotiswar  If you want to , you can.
