### ISSUE TITLE
Download functionality

### ISSUE THREAD

**Issue by jahir-raihan** [jahir-raihan/calendar-generator#4]
As of our functionality requirements, It was meant that there will be a download functionality for downloading current calendar year in PDF format. 

**But the functionality still not available till now!**

## Enhancement

> - Anyone with good knowledge of javascript can implement this feature using js libraries. 

![Screenshot 2023-08-23 at 9 29 11 PM](https://github.com/jahir-raihan/calendar-generator/assets/78207450/df27b9e7-1660-4d4c-b8f0-b06f5fbe9231)

**Comment by KWangechi** [comment]
Hello @jahir-raihan I have created a pull request for this issue. 

Looking forward to your feedback.
