### ISSUE TITLE
Make the copyright `year` dynamic

### ISSUE THREAD

**Issue by jahir-raihan** [jahir-raihan/calendar-generator#40]
Currently the copyright year is static. Eg: It is given `2023` statically. 
It will be more efficient where able to set it dynamically. 

Eg: For year `2024` It should set it's value `2024`

Hint: 

> - Use javascript `Date` library to make it happen.

![Screenshot 2023-09-05 at 2 49 42 PM](https://github.com/jahir-raihan/calendar-generator/assets/78207450/6fd9008b-0c3d-4816-bb2c-70aee788aad5)

**Comment by corners2wall** [comment]
Hey, I am ready fix this. Assign to me please

**Comment by jahir-raihan** [comment]
@corners2wall Hello Thank you for looking into it. There is no assignees , you can open a pull request and submit it, you're changes will be merged if theres no issue. Happy Coding !
