### ISSUE TITLE
Add  Footer  with copyright text.

### ISSUE THREAD

**Issue by jahir-raihan** [jahir-raihan/calendar-generator#8]
One thing to notice, that there is no footer in the website. 

## Hint
> - Add a Footer tag at the bottom of the website.
> - Add `[copyright sign] Copyright 2023 @Calender Contributor Team.`
> - Align the copyright text to center.

**Comment by KWangechi** [comment]
I created a pull request for this. You can have a look at it on: #10

**Comment by KWangechi** [comment]
Please see open PR above
